window.catacombsFullNotes = {
  "source": "C:\\Users\\chiar\\OneDrive - Institute of Tourism Studies\\Documents\\Jones Teams Rabat\\St Paul Catacombs Compilation Final.docx",
  "intro": [
    "St Paul Catacombs",
    "Once you learn one temple you learn how to guide at all of them: same for catacombs",
    "The builds on Classical and Medieval theory class, based on the assumption that we know.",
    "Core books:",
    "Anecdotes narrative etc will come from readings.",
    "She will provide us with all the information and we must be able to select accordingly to what group there is in front of you.",
    "------------------------------------------------------------"
  ],
  "stops": {
    "0": {
      "title": "General Introduction to the Catacombs",
      "paragraphs": [
        "[Visitors centre Room 1 - TVP Poster Plan - talk about how the site developed - excavations, discoveries, site size, type and number of tombs/ burials]",
        "Entrance",
        "We are standing at the outskirts of Melite. The ditch and walls ended around the area of St Paul's Church. Santa Rita Street marks the area of fortification; the wall of the old Roman Citadel.",
        "Area undermined with tombs : we are standing on a necropolis - a city of dead.",
        "These have been sectioned example St Paul's (owned by the state), St Agatha's (owned by the missionaries (check exact name of these)), private ones, a cluster belonging to Wignacourt museum etc.",
        "Under most houses in Rabat there are tombs; some are used, some not, some are even wine cellars. Certain tunnels are walled off as they keep going under private houses.",
        "St Paul's is comprised of circa 2,000 square metres - largest complex in Malta",
        "Between 1,000-5,000 people were buried here. We do not have the exact number as, despite being part of written history, here historians still heavily depend on archaeological findings.",
        "Malta was a small corner of the Roman empire, so unimportant it was not written about.",
        "It was built during the 4th - 8th centuries CE (Common era) then abandoned.",
        "She does not use AD since it has a strong Christian link",
        "They were reutilised around the 13th century by early Christians.",
        "This is normal, can be compared to modern day reusing of older buildings; we do not demolish buildings but reuse them.",
        "Roman period in Malta dates back to 218 BCE, with the 2nd Punic War.",
        "Prior to this we had the Punics/ Carthaginians and before that the Phoenicians.",
        "Roman Rule lasted 700 years and so it cannot be discussed as 1 solid period: political, economic, and cultural changes occurred throughout it. During the first centuries, Punic traditions lingered.",
        "When people live in misery and poverty, they do not have time to build a catacomb. We believe there was a good economic period: indicates prosperity. Same mentality as prehistoric temples.",
        "How were they created? From an exisiting \"cemetery\". What did people do?",
        "They found existing Punic tombs, adopted them, and bit by bit, added on chambers.",
        "This site is made of two parts:",
        "Eastern (visitor centre)",
        "Western (were most compounds are found)",
        "TVP - Top Visual Priority: Essentials for guides.",
        "Tell me and I forget, show me and I remember",
        "Punic shaft & chamber tombs on the floor",
        "Roman practices similar to Punic and Greek: inhumation & cremation",
        "Remember these are copy at cultures: Egypt - Phoenician - Punic - Greek - Roman (Chiara check this order pls)",
        "Punic and Romans believed in life after death: city of the dead",
        "City = alive, not the end; rebirth into the afterlife",
        "That's why they buried objects with them: items useful to loved ones in after life",
        "Precious objects - target for tomb raiders",
        "At one point, knights issued licenses to grave robbers to gather tax or a percentage of commission.",
        "Cata - below",
        "Cumbas - hollow",
        "From Greek referring to hollow ground below (below hollows)",
        "Catacombs are found on the roads leading to Rome, but not in Rome.",
        "They are presented in long corridors with tombs found on either side.",
        "In Malta they are different, called hypogea. It is only the main complex, no. 1 on map, which is similar (it is a Christian one).",
        "Symbols found during excavations revealed compounds could have belonged to:",
        "Guilds - groups of a particular craft or skill ex. Guild of surgeons, bakers, tin smiths.",
        "Ethnic or religious groups - marked by symbols:",
        "Jews - menorah 🕎",
        "Christians - chi-rho (symbol for early Christians) ☧",
        "Pagans - bull",
        "a. Geographical context, right outside the walls of ancient Melite in the area",
        "popularly known as ‘Tad-Dlam’, along with other catacombs in the area (such",
        "as St Agatha’s, St Cataldus, Abbatija tad-Dejr, etc);",
        "b. Underground necropolis (city of the dead) – movement from familial to",
        "communal;",
        "c. Main communal catacombs (2,000 sq.m.) + 22 other smaller catacombs (a",
        "total area of c. 10,000 sq.m.);",
        "d. Origin from late Phoenician Period (quarry), to Punic/early Roman cemetery",
        "with shaft&chamber tombs, followed by the creation of catacombs from 4th",
        "century AD used up to 8th/9th century AD by pagans, christians and jews;",
        "e. As site of archaeological, social, cultural and religious significance that has",
        "also obtained recently the European Heritage Label.",
        "Additional NotebookLM notes to add",
        "• The Landscape of the Dead: We are standing on a necropolis - a literal \"city of the dead\" - located at the outskirts of ancient Roman Melite. The site spans approximately 2,166 square metres, making it the largest complex in Malta.",
        "• Historical Timeline: Roman rule in Malta began in 218 BCE during the Second Punic War, but these catacombs were mainly constructed between the 4th and 8th centuries CE. They were later abandoned and reused in the 13th century during the re-Christianisation of the island.",
        "• Archaeological Origins: The site evolved from earlier Phoenician and Romano-Punic shaft-and-chamber tombs. These tombs were packed so closely together that chambers often broke into one another, encouraging the later connection of spaces into long, narrow corridors.",
        "• The Discovery: Antonio Bosio, born in Malta in 1575, can be presented as the “Christopher Columbus” of the catacombs because of his lifelong study of Roman catacombs. The systematic clearance and investigation of St Paul’s Catacombs was led by Dr A. A. Caruana in 1894.",
        "• The Population: Estimates suggest between 1,000 and 5,000 people were buried here. Historians rely heavily on archaeology because Malta was a small and rarely documented corner of the Roman Empire.",
        "Additional YouTube notes to add",
        "The Rabat catacombs fascinated visitors, antiquarians and archaeologists for centuries because many remained accessible until relatively recent times.",
        "Early written references begin with Marc Antonio Axiaq around 1610, who described rock-cut burial spaces with pits for corpses and smaller holes for infants. Francesco Abela later gave a fuller account in Descrittione di Malta (1647), distinguishing pagan and Christian hypogea and recording that St Paul’s Catacombs were accessible through a small hole. He even took visiting dignitaries through the tunnels.",
        "Later writers included Onorato Bres, G. P. Badger, Achille Ferris, Cesare Vassallo and Antonio Annetto Caruana. Caruana’s 1894 cleaning, study and survey of St Paul’s Catacombs was especially important, even though he still believed the catacombs were mainly Phoenician. His work recorded the condition of the site before later interventions.",
        "International interest increased after Caruana. Albert Mayr visited Malta at the end of the nineteenth and beginning of the twentieth century, and later German scholarship studied the Christian and Jewish catacombs. Sir Themistocles Zammit also excavated many tombs in the wider Taċ-Ċagħqi cemetery zone.",
        "Professor Mario Buhagiar’s 1986 study became a key modern reference for Maltese catacombs, but because the site had long been open to the public, little physical excavation work had been carried out for many years.",
        "Heritage Malta later launched a €4.2 million conservation and interpretation project, 85% funded by the European Regional Development Fund. The project included archaeological investigations, environmental studies, conservation work and major visitor improvements. The number of catacombs open to the public increased from two to more than twenty, across around 10,000 square metres, with eight main interpretation points.",
        "The wider Rabat and Mdina area was attractive for settlement because of its central, defensible position, water supply and fertile land. Settlement goes back to the Bronze Age, and Melite probably became Malta’s main administrative centre in the Phoenician period.",
        "Archaeology suggests that the area outside Melite’s walls was first used as surface quarries. The stone removed may have been used to build ancient Melite. The quarry terraces were later reused as a burial ground during the later Phoenician and Punic periods, around the fourth and third centuries BC.",
        "The cemetery developed from smaller shaft-and-chamber tombs into larger communal catacombs. Earlier Romans often preferred visible family tombs, but later Roman and Byzantine communities increasingly preferred group burial: a community of the dead.",
        "The cemetery was used by pagans, Christians and Jews, and it is one of Malta’s main physical sources for the Byzantine period. By the end of Byzantine rule, its use as a burial ground had ended. Later medieval reuse transformed some areas into churches or oratories.",
        "The recent archaeological project confirmed quarrying, shaft-and-chamber tombs, cremation deposits, infant amphora burials, dumps, repeated tomb reuse and surviving in-situ remains. Tomb 15 produced a female skeleton with vessels, a net-weaving needle, a face pendant, a glass bottle and a bone hairpin still beneath the skull. Tomb 31 produced coffin clamps, bronze needles, glass bottles, lamps, a coin, imported ceramics, cremated remains and scientifically excavated wood fragments.",
        "One rare personal detail is the lead inscription mentioning Fufi/Fufia Galena and Custus/Custodius Adienus, husband and wife, who acted in memory of Valeria, described as well-deserving. Valeria is therefore one of the few named people known from the Rabat cemeteries.",
        "Conservation starts on site as soon as fragile objects are discovered. Artefacts are lifted carefully, taken to laboratories, cleaned, conserved and sometimes excavated further in controlled conditions. This applies not only to display objects but to any material that can preserve information."
      ]
    },
    "1": {
      "title": "An elite man's funeral procession",
      "paragraphs": [
        "[Visitors' centre Room 2 - TVPs wall poster - funerary artefacts display cabinets]",
        "Exhibit Room",
        "a. High child mortality rate (only 3 out of every 5 lived beyond 1 yr, and",
        "exceptional if living beyond 40 yrs);",
        "b. Strong link between life and death;",
        "c. Lemuria with rituals to appease the evil spirits (such as offerings of",
        "beans).",
        "The Roman Funeral:",
        "a. A true show with the funerary procession – the pompa funebri, complete",
        "with mimes, musicians & hired female mourners to lament and sing, and",
        "a eulogy;",
        "b. 9-day mourning period;",
        "c. The cult of the ancestors (the lares & death masks).",
        "These tombs were not for everyone: those who could afford it, elite or rich families.",
        "If not, had the option to join a club; collegiata (confirm spelling)",
        "Monthly fee: would take care of burial rites & funerary process, also cared for the widow",
        "Elite and middle class who afforded the club fee",
        "Poor people: a hole dug and person thrown in",
        "Toxic people - Murderous person, witch, thief, criminal, etc. - taken alive to an isolated place as far as possible & left there to be eaten by wild animals, ex wolves.",
        "Malta did not have such types of animals: maybe they were burnt? Or taken to an isolated area where the pollution could be left out",
        "Photo of the Pall bearers",
        "Funerary ritual of an elite person:",
        "They were washed and embalmed, then placed on a coach or table in the atrium - central part of a persons home (double check)",
        "The very elite would be left for 8 days: called lying-in state",
        "This allowed people to come pay their respects, ex. Political person would receive visitors from Sicily",
        "Very complex ritual for the elite which involved:",
        "Family",
        "Slaves",
        "Servants",
        "Relatives",
        "Engaged people as:",
        "Mourners",
        "Eulogists",
        "Actors",
        "Family: normally ladies head covered in a veil and men left uncovered, during funeral, the contrary.",
        "Idea of subversion, upside down thing",
        "Pall bearers - usually the freed slaves of the person (these would not wear hats)",
        "Primo genito - first born son",
        "when a male died, a cast of the face (wax mask) was made",
        "Next in line would walk carrying the face masks of previous generations, ex father & grandfather",
        "Make a bust",
        "Freed slaves - presented hat showed was a slave",
        "Presented in a thoughtful position; I am free but what will happen to me now? I have no master - unknown future",
        "Mimes - actor would mimic the dead ones",
        "Mourners - bikkejja, paid to follow the procession and cry",
        "Sometimes their tears were gathered in a jar and then buried with them",
        "This would allow the dead to wake up and see \"how loved\" he was",
        "Musician - led procession, flute and horn",
        "Eulogist - man engaged to cry out about the heroism & greatness of the deceased ex. Great politician, much loved",
        "Once the procession reached the opening of the tomb, the externals would not enter the catacomb but only close family would.",
        "We are a product of our past - I don't remember what this had relevance to but I liked the quote",
        "It leaves more questions than it answers.",
        "Additional NotebookLM notes to add",
        "• Preparation & Lying-in-State: For elite funerals, the body could lie in state for up to eight days, placed on a couch or table in the atrium, the central heart of the home. This allowed political peers and visitors, possibly even from Sicily, to pay their respects.",
        "• The Pompa / Procession: Funerals traditionally took place at night by torchlight. This may have had practical reasons, such as hygiene and smell, and religious reasons, such as avoiding the evil eye.",
        "• Musicians: The procession could be led with flutes and horns.",
        "• Mourners (Bikkejja): Paid professional mourners followed the procession crying. Their tears were sometimes collected in jars and buried with the deceased to show how loved the person was.",
        "• Actors / Mimes: Actors could mimic the deceased’s mannerisms, keeping their memory alive during the walk to the tomb.",
        "• The Family: The funeral involved ritual subversion: women covered their heads with veils while men left theirs uncovered, the opposite of daily custom.",
        "• The Mask Bearer: The first-born son or next in line could walk carrying wax masks of previous generations, creating a physical link with the ancestors.",
        "• Freed Slaves: Freed slaves could serve as pallbearers. Their uncovered heads and thoughtful posture symbolised their new freedom, but also the uncertainty of a future without a master.",
        "Additional YouTube notes to add",
        "Death was treated as a major ritual moment. Mortuary rites helped mourners express grief, accept death, celebrate the deceased and reinforce beliefs about the afterlife.",
        "Across cultures, three elements are usually present: funeral ceremonies, a sacred or set-apart place for the dead, and remembrance of the dead.",
        "The body was washed, sometimes with perfumed oils, and wrapped in cloth bandages. Lamentation could include sackcloth, tearing hair and beating breasts.",
        "Objects could accompany the dead because they were believed useful or protective in the afterlife: food, coins, ceramic vessels, figurines and personal possessions. Magical or protective objects could also be included.",
        "Egyptian amulets were common protective talismans. Phoenician and Punic culture absorbed Egyptian religious elements, including protective gods and goddesses. A small papyrus found in a tomb outside Rabat includes a prayer invoking Isis to defeat an enemy blocking a sea journey to the underworld.",
        "Roman funeral ritual began at the deathbed. Relatives gathered, the closest relative gave the farewell kiss and closed the eyes, and mourners began the conclamatio, repeatedly calling the dead person’s name to announce death within the household.",
        "A wax death mask could be taken and kept in the atrium with ancestral masks, linking the deceased to the family line and cult of ancestors.",
        "A coin could be placed with the deceased to pay Charon, the ferryman who carried the dead across the River Styx to Hades. This was similar to earlier Phoenician customs.",
        "Poorer people could be taken for burial at night in simple processions. Wealthier citizens could have a public and theatrical funeral with musicians, paid mourners, mimes, freed slaves and relatives.",
        "A professional funerary organiser, transcribed as libitinarius, could be hired to arrange the preparations. At the cemetery, the body could be placed in a grave, built tomb or sarcophagus, although sarcophagi have not been found in the Maltese Islands."
      ]
    },
    "2": {
      "title": "Inhumations and Cremations",
      "paragraphs": [
        "Showcases around the room:",
        "[Visitors' centre Room 2 - TVPs mock tomb - showcases displaying crematory pots and tomb markers]",
        "Jars could have held tears or balms",
        "Horse statuettes found in tombs - one interpretation = child's toys",
        "Loom weights",
        "Coin - placed in mouth of deceased to pay passage to the ferry man",
        "Charon is the mythological Greek ferryman who transports souls of the deceased across the rivers Styx and Acheron to the Underworld.",
        "From <https://www.google.com/search?q=ferryman+charon&oq=ferryman+sharon&gs_lcrp=EgZjaHJvbWUqCQgBEAAYDRiABDIGCAAQRRg5MgkIARAAGA0YgAQyCQgCEAAYDRiABDIICAMQABgNGB4yCAgEEAAYDRgeMggIBRAAGA0YHjIICAYQABgNGB4yCAgHEAAYDRgeMgoICBAAGAoYFhgeMgoICRAAGAUYDRge0gEINDU4NmowajeoAgCwAgA&sourceid=chrome&ie=UTF-8>",
        "Amphorae",
        "Typical shaft & chamber tomb - Punic origins",
        "We know they had coffins, however, the only thing remaining is metal clamps and nails",
        "Sometimes children were buried in amphorae",
        "Even animals",
        "It was important to make offerings to ancestors - honey or milk was periodically poured through holes in the slab or terracotta covering the dead. These would occur on the birthday, death anniversary or week for the dead.",
        "It is said that there was a practice of sacrificing a young, virgin lady - it pays you to not be a virgin",
        "Funerals for the poor would have been done at night potentially:",
        "To avoid the evil eye",
        "To not make it a public event",
        "Outside burial walls:",
        "Hygiene - smell & viruses",
        "Religious notions",
        "The polluted vs the pure",
        "There was even a law to bury the dead outside.",
        "Tomb markers - some were decorated, plain or held inscriptions",
        "Curriculum - description of the deceased ex child of…, much loved etc.",
        "Grave goods:",
        "a. Personal decorations (such as the Egyptianizing faience pendant of Horus",
        "or the bead bracelets buried with children to ward off evil spirits);",
        "b. Other objects reflecting the deceased job and/or interests (such as the",
        "dice and the small rooster figures);",
        "c. Coins to pay the ferryman Charon, for carrying the deceased over the river",
        "Styx to the underworld (Hades);",
        "d. Pottery containers, perhaps used as part of the funerary meal, and",
        "ensuring the dead have all they need in the afterlife.",
        "5) Reconstruction of a tomb & tomb-markers:",
        "a. Fossores;",
        "b. Different types of tombs, reflecting social status and financial power –",
        "location and decoration are other indicators;",
        "c. Window tomb as a local development;",
        "d. Bodies shrouded or in coffins (first scientifically excavated wood",
        "fragments from such contexts);",
        "e. The buried pig (feasting & sacrificial);",
        "f. Tomb-markers (limited and basic locally but elaborate ones know",
        "abroad).",
        "6) Stories and Legends:",
        "a. Hideout for Christians during time of persecution;",
        "b. The pig that fell in and came out in Siggiewi;",
        "c. That the spaces were dug by giants;",
        "d. Already attracted antiquarian interest (GF Abela);",
        "e. Association with St Paul as it was believed it connected to the grotto;",
        "f. First archaeological survey in 1894 by A. A. Caruana;",
        "g. Abused spaces… looted, quarried, used as ancient dumps, as animal",
        "pens and as shelters during WWII;",
        "h. Recent project which included extending the public areas of the site,",
        "conservation works, environmental monitoring, archaeological",
        "excavations, Ground Penetrating Radar survey & enhanced interpretation.",
        "Additional NotebookLM notes to add",
        "• Competing Traditions: The site reflects a shift in funerary fashion. Cremation was common in earlier Roman practice, while inhumation became standard for Christians for theological reasons.",
        "• Class Distinctions - The Rich: Wealthier people could be buried in richly carved sarcophagi made of marble, stone, terracotta, lead or even wood.",
        "• Class Distinctions - The Poor: Poorer people could be carried on a cheap bier, called a sandapilla, and placed directly in simple trench graves, or fossae, usually fully extended.",
        "• Grave Goods: Tombs could contain oil lamps, horse statuettes, possibly children’s toys, loom weights and other personal or symbolic objects.",
        "• The Obol: A coin could be placed in the mouth or between the teeth of the deceased to pay Charon, the mythological ferryman, for safe passage across the River Styx.",
        "• Tomb Markers: Markers called sema helped proclaim the identity of the deceased and ensured that the dead were not forgotten.",
        "Additional YouTube notes to add",
        "Inhumation means burial of the body. In Malta, the shaft-and-chamber tomb was the typical early tomb form for millennia: a deep shaft leading to one or two burial chambers where bodies and objects were placed.",
        "Inhumations could take place in shaft-and-chamber tombs, larger chamber tombs, floor tombs, arcosolia, window tombs and later catacomb forms.",
        "Cremation was also practised. One simple type was the bustum, where the body was burnt in a shallow grave filled with dry wood and then covered with earth.",
        "A more common cremation form used a large altar-shaped pyre. Objects closely connected with the deceased, together with incense and perfumes, could be thrown onto the pyre.",
        "After the pyre was consumed, the closest relatives extinguished the embers with water and wine. The ashes and burnt bones were collected, dampened with milk and wine, and placed in an urn.",
        "Excavations at St Paul’s found urns and cooking pots containing burnt human remains. Some were closed with plates and lamps could be placed on top.",
        "Tomb 31 contained cremated remains once held in at least two urns, although these had probably been emptied by grave robbers.",
        "An almost complete pig skeleton found beside one urn may suggest a connection with a funerary meal or sacrificial/feasting practice.",
        "Babies could be buried in amphorae used as coffins. Two baby amphora burials were found during excavation, one with a cup and small lamp inside. Similar infant amphora burials are known elsewhere in Rabat.",
        "Amphorae are important because they can show trade contacts and help date archaeological layers. One amphora from the site was Cypriot and dated to the end of the first century AD."
      ]
    },
    "3": {
      "title": "Garden + Social Pavillion + Archaeology Pavillion",
      "paragraphs": [
        "Outside Garden",
        "Hawn hekk sparat tigri so mghandix idea xintqal, pero hemm:",
        "I think ventilation holes for the catacombs? - need to check this, teorija ta Chiara",
        "Social Pavillion",
        "Archaeological Pavillion",
        "Additional NotebookLM notes to add",
        "• Modern Infrastructure: The garden contains ventilation holes that once allowed air into the subterranean galleries. The Visitor Centre pavilions present some of the most striking modern discoveries.",
        "• The Story of “Elsa”: In 2013, while preparing the Visitor Centre foundations, archaeologists used Ground Penetrating Radar (GPR) and located a 1st- to 2nd-century CE shaft-and-chamber tomb.",
        "• Forensic Reconstruction: Inside was a skeleton nicknamed “Elsa”. Beside her were a bone hairpin, a face pendant and a glass unguentarium. Her face was reconstructed using clay layers over a 3D model of her skull, with an anthropometric study of contemporary Sicilian women used as reference. The result gives visitors a direct human connection to the past.",
        "• The Social Aspect: The pavilions show how catacombs inspired literature and traditions about the underworld, martyrs and the 17th-century “martyrdom mania”, when bones were uncovered and sold as holy relics.",
        "Additional YouTube notes to add",
        "The garden and pavilions help present the site as a long-lived landscape rather than just tunnels: quarry, cemetery, catacomb system, reused space and modern conserved heritage site.",
        "The Social Pavilion is useful for explaining memory and folklore. Dark underground places fascinated and frightened people, and the catacombs inspired local stories.",
        "Popular stories claimed that Christians hid there from Roman or Muslim persecution, that giants dug the caves, that a pig entered the catacombs and emerged elsewhere, that a class of children was lost and their voices could still be heard, and that St Agatha used the catacombs to hide from persecution.",
        "The transcript stresses that many of these stories are fiction. The catacombs were primarily cemeteries, not hiding places. The Romans knew where they were, and hiding among decomposing bodies would not have been practical.",
        "Even fictional stories matter because they shaped local memory and sometimes entered publications as if they were fact.",
        "The Archaeology Pavilion explains the modern excavation project: archaeologists investigated both the catacombs and the spaces above and around them, confirming quarrying, shaft-and-chamber tombs, cremation, infant amphora burials, dumps and repeated tomb reuse.",
        "Important finds to mention include Tomb 15 with vessels, net-weaving needle, face pendant, glass bottle and hairpin; Tomb 31 with coffin clamps, bronze needles, glass bottles, lamps, a coin, imported ceramics, cremated remains and wood fragments; plus lamps, unguentaria, bone dice and articulated human bones from other tombs.",
        "The pavilions also help explain conservation. Fragile objects are protected from the moment they are discovered, lifted carefully, cleaned and stabilised in laboratories. This is slow and expensive but preserves information for future study."
      ]
    },
    "4": {
      "title": "Main Complex",
      "paragraphs": [
        "(include info on size of site and development) – loculi - Staircase [talk about loculi and infant mortality]",
        "No1. Complex",
        "Chi-rho symbol - first two letters of Christ in Greek ☧",
        "Emperor Constantine (Constantine the Great) adopted this for early Christians - he was responsible for the spread of Christianity",
        "There are the old 18 steps which can be seen below the modern ones.",
        "Warn about the:",
        "Steps",
        "Darkness",
        "Very very, enclosed",
        "People may have fear of darkness or claustrophobia. It is your responsibility to warn them. They can wait in the coffee area across the street whilst you enter.",
        "Loculi - Wall tombs could be for kids or adults",
        "Infant loculi - large amount found, shows high child mortality rate, possibly even at childbirth",
        "The most vulnerable; young and old.",
        "Additional NotebookLM notes to add",
        "• The Entrance: The descent includes a staircase where the original 18 rock-cut steps can still be seen beneath the modern replacements. Visitors should be warned about darkness, enclosure and possible claustrophobia.",
        "• Infant Mortality: The corridors contain many loculi, small rectangular wall recesses used almost exclusively for children and babies in Malta. Their number illustrates the tragically high child mortality rate of the period.",
        "• Family Bonds: Multiple small loculi are often clustered around a larger “parent” tomb, suggesting a family unit remaining together in death. In some cases, children were buried in repurposed amphorae.",
        "Additional YouTube notes to add",
        "The word catacomb comes from Latin catacumbae, originally referring to an area of underground tombs on the Appian Way in Rome. Its exact origin is uncertain, but it may mean something like 'at the graves'. Today it is used for underground hypogea, especially late Roman rock-cut cemeteries.",
        "Catacombs began as small underground burial places, possibly for families, and expanded as the living population grew and above-ground burial space became limited.",
        "The main communal catacomb at St Paul’s was gradually extended to more than 2,000 square metres and could accommodate hundreds of people. The wider St Paul’s complex covers around 10,000 square metres and includes twenty-three catacombs.",
        "The main catacomb was probably the principal communal catacomb of ancient Melite, and its size suggests a substantial population.",
        "Although catacombs exist elsewhere in the Roman world, especially Rome and Sicily, Maltese examples are distinctive because of local island traditions. The rock-cut Agape tables/triclinia are among the clearest local features.",
        "Catacombs were not only Christian. They were used first by pagans and later by pagans, Christians and Jews, generally in separate catacombs or sections, recognised through symbols and architecture.",
        "At the main complex, explain tomb variety as a sign of status, family identity and sometimes profession. Family tombs could be reused and enlarged, rather like modern family graves.",
        "Loculi are shelf-like wall cuts. In Malta they were used almost exclusively for infants and children, reflecting high infant mortality and the need to use every available space. They could be added wherever space permitted, including walls and tomb façades.",
        "Fossores, or gravediggers, cut tombs into the soft rock. They used tools similar to stonemasons: pickaxes to remove large chunks, more controlled tools such as the dolabra for refined cutting, and chisels for finishing.",
        "Wealthier clients could pay for a smoother mortar finish made with lime and crushed pottery, suitable for painted decoration.",
        "Tombs could be decorated with painted motifs, farewell messages, crosses, menorahs, carved pillars and other symbols. Closures ranged from thin slabs fixed with mortar to plug doors, stone doors with key-and-lock systems and large monolithic lids."
      ]
    },
    "5": {
      "title": "Tables and Apses [Funerary Triclinia]",
      "paragraphs": [
        "Talk about the Roman funerary meal, called a ‘silicernium’",
        "In the open space downstairs",
        "Most of what is said, needs to be discussed in the visitor centre or garden. Do not try to guide in the corridors",
        "Monitor chaos and number of groups to see whether to explain outside or below.",
        "Mensa - found at heart of the complex",
        "The area is likely (not sure) where the funeral meal would have happened - around the tables called agape, mensa or triclinium.",
        "The meal was called refrigeria plural of refrigerium - refreshment",
        "These tables are different to other food tables in Ancient Roman worlds.",
        "The most similar were found in Sabratha, Libya.",
        "Their reclining sides allowed people to lay on their sides as they sat .",
        "The funerary meal (refrigerium) and the triclinium or agape table",
        "(mensa/table with stibadium/bench) – officially abolished in 692AD.",
        "Roman meals also at the end of the mourning period and on the",
        "Parentalia;",
        "How & when were these used?",
        "There are two theories for the dent in the \"rock table\":",
        "Where the servant would stand",
        "Drain - more possible as there is what looks like a channel below it",
        "Additional NotebookLM notes to add",
        "• The Agape Table: At the heart of the complex are circular tables hewn directly from the living rock. They are among the most distinctive features of Maltese catacombs and functioned like a rock-cut Roman dining room, or triclinium.",
        "• The Ritual (Refrigerium): These tables were used for the refrigerium or silicernium, a refreshment or funerary meal held to honour the dead, including on anniversaries.",
        "• Design and Function: The table surface is flat, with a rim of around 3cm and a small opening, probably used to wash and drain the surface after the meal. The tables are roughly 75cm in diameter and stand on a low platform with sloping sides that imitate reclining couches.",
        "• The End of the Feast: In early Christianity these meals became viewed as exaggerated, with rumours even suggesting orgies, and an official order was later given to destroy such tables. In Malta, many survived intact.",
        "Additional YouTube notes to add",
        "One of Malta’s most distinctive catacomb features is the rock-cut funerary table, often called an Agape table or triclinium. It was used for meals commemorating the dead.",
        "Such meals were known across the Roman world, but in Malta the tables survive almost intact and were carved directly from the living rock.",
        "A ceremonial meal or banquet could take place over the grave to mark its closure and completion. Libations, incense and offerings of food and drink could be made to the deceased.",
        "In earlier catacombs, some blocking stones for cubicula had channels that allowed liquid offerings to pass into the burial chamber.",
        "Over time, offerings developed into formal funerary meals held at the end of the funeral. In Roman practice this marked the start of dies feriae, a nine-day mourning period, which ended with another commemorative meal.",
        "The Roman funerary meal is commonly called the silicernium. At St Paul’s, the triclinia show how important these meals were socially and ritually.",
        "The tables were used by pagans and Christians, so their presence alone does not prove a catacomb was Christian. Religious identification needs symbols or other evidence.",
        "The pig skeleton found beside a cremation urn may connect to funerary eating, sacrifice or ritual feasting. It shows how food, drink, lamps and incense linked the living with the dead."
      ]
    },
    "6": {
      "title": "Burials",
      "paragraphs": [
        "– talk about burial rites and the different types of tombs found in Malta [TVPS the Arcosolium – floor tombs - Window Tombs etc.]",
        "Acrosolium in front of the agape - shows feasting was a great deal",
        "Tables indicate some kind of offering or feasting.",
        "We have no evidence but, comparing to example Pompei, however, they are still similar.",
        "(ma tantx fimtha din il bicca l ahwa)",
        "Fossores - were grave diggers",
        "Used pick and axe",
        "By time, gained status, like a construction company. The elite would hire them to build more tombs for them.",
        "Collegiata of elite families would contact the fossores.",
        "They had a map of the tombs; allowed foreigners travelling here to pay their respects",
        "Wall & floor tombs - cheapest burials: lower part of the elite",
        "Imagine the smell, insects and cockroaches found here. During this period of time, people did not live long - till around 40.",
        "Society was plagued by viruses, many through use of such catacombs - feasting with fermenting bodies of the dead.",
        "People did not have our knowledge of cleanliness.",
        "Covered with slavs or terracatorra, then sealed with plaster.",
        "Holes in the wall for light, lanterns, candles.",
        "Important: in early Christianity, at one point there was an order to stop using agape tables and so most of them were destroyed. This was because feasting became exaggerated, including orgies. Malta did not have orgies so they did not destroy them.",
        "Additional NotebookLM notes to add",
        "• Preparation Rituals: At death, the nearest relative would close the eyes and mouth, sometimes attempting a final kiss to “catch the soul”. Women of the family washed the corpse, preferably with seawater, as a rite of passage.",
        "• Dressing the Body: Men could be buried in a Roman toga, while those who died young were sometimes laid out in wedding attire.",
        "• Window Tombs: A common tomb type with a square opening, often 80-100cm above floor level, leading to an oval chamber with rock-cut pillows.",
        "• Arcosolium: A tomb with an arch and sill cut into the wall. Maltese versions are smaller than Sicilian examples and usually held only two or three people.",
        "• Floor Tombs / Forma: Simple graves cut into the floor, later sometimes reused as ossuaries to hold bones from several individuals.",
        "• Rock Pillows: Semicircular cavities in the stone where the head was rested. These indicate the capacity of each grave.",
        "Additional YouTube notes to add",
        "Choosing a tomb meant choosing the deceased’s eternal resting place. Location, tomb type, decoration and closure all reflected status, wealth and sometimes family identity.",
        "Roman law forbade burial within city limits, so cemeteries and catacombs were outside the city walls. Wealthier families could choose private catacombs or prominent positions within public ones.",
        "The cheapest Maltese catacomb tomb type was the floor tomb, a rectangular pit cut into the ground. These were often dug into corridors, meaning visitors physically walked over them.",
        "Loculi were also relatively cheap. In Malta they were mainly for infants and children, unlike Rome and Sicily where they were more broadly used. Their number reflects high infant mortality and limited space.",
        "Arcosolia were more expensive and very common. An arcosolium is a tomb cut under an arch, with the body placed in troughs or on a shelf. Rooms with arcosolia on three sides could be sealed off from the rest of the catacomb.",
        "Window tombs were more sophisticated and seem to be a local development. They consist of a burial chamber accessed through a window-like opening inside a small niche. They are common in rural Maltese catacombs but less frequent in the main Rabat catacombs.",
        "Window tombs could look intimate and elegant, often with small flanking pillars and carved or painted decoration.",
        "Burial rites usually included washing the body, treatment with oils where possible, wrapping in cloth, lamentation, and the placing of objects such as food, coins, ceramics, figurines, lamps, unguentaria, personal belongings and protective amulets.",
        "Christian symbols include the cross, palm branch, fish and anchor. However, because pagans and Christians used similar tomb architecture and funerary meals, symbols are needed before identifying a tomb as Christian."
      ]
    },
    "7": {
      "title": "Baldacchino and Saddleback Tombs",
      "paragraphs": [
        "Talk about elite burials",
        "Very rich important Tombs",
        "In order of eliteness:",
        "Saddle back tomb - very elite",
        "Placed through a window",
        "Many bodies found here - place reutilised by many generations of the same family (consider the cost)",
        "Hole on the side - grave robbers used to steal very, very precious items",
        "Baldacchino tomb - On other side",
        "Acrosolium",
        "2 unique features of the catacombs in Malta:",
        "Pillow - head rests: cavities in stone, cushion for head",
        "Double grave - mystery? Maybe for married couple? Siblings? Died at the same time?",
        "Infant loculi - large amount found, shows high child mortality rate, possibly even at childbirth",
        "The most vulnerable; young and old.",
        "Point out 2 things (peace sign photos):",
        "Wall - leads to private houses",
        "Tombs on the right - may have belonged to a collegia",
        "Further in, one finds elite tombs.",
        "The main burial space within the catacombs consists of a hall with 11 baldacchino tombs that divide the area into two corridors. The remains of a mural can still be seen on one of these tombs.",
        "The mural, painted in red ochre, shows a seated figure with the word “farewell” painted above it, together with the representation of an anchor, symbolising hope.",
        "Additional NotebookLM notes to add",
        "• The Elite Tier: Baldacchino and saddleback tombs represent the highest-status burials within the catacombs.",
        "• Baldacchino Tomb: A free-standing sarcophagus with four corner pillars supporting a rock-cut canopy or vaulted ceiling. Its size and visibility marked great distinction.",
        "• Saddleback Tomb: A variation of the canopied tomb with a top cover shaped like a horse’s saddle. These were expensive to carve and were often reused by several generations of the same family.",
        "• Evidence of Robbery: Many elite tombs have holes in the side, evidence of grave robbers targeting precious objects buried with the dead.",
        "Additional YouTube notes to add",
        "For wealthy people who wanted to be remembered visibly, the baldacchino tomb was the most striking option.",
        "A baldacchino tomb is a free-standing canopied tomb with a roof supported by four pillars and arches. Its position, proportions and decoration show that it was meant to be seen.",
        "These tombs usually occupy important focal points in the catacomb. They could be plastered, painted or covered with stone slabs to create a smoother and more prestigious finish.",
        "The body could be placed in troughs accessed from above or in a chamber reached through a small side opening.",
        "Closures could be simple flat slabs or more elaborate pitched lids known as saddleback lids.",
        "The headrests carved into some tombs evoke beds for the living and link to the idea of koimeteria, or sleeping places. This connects especially well with the Christian idea of death as sleep before resurrection.",
        "Elite tombs displayed status through visibility, location, architectural form, painted or carved decoration, finish and the type of closure used."
      ]
    },
    "8": {
      "title": "The crypt",
      "paragraphs": [
        "[Part of the catacombs were reutilised during the re-Christianisation of the Island, around the 13th century - an underground early Christian place of worship] – talk about Christianity in Malta",
        "We then walked back to the rock cut church.",
        "Room on the left of the entrance done in the 13th Century by early Christians.",
        "Doric - peristyle columns dug into the rock",
        "Frescoes on the ceiling",
        "Early Christians worshipped underground because they were persecuted - space for worshipping",
        "No.3 compound likelihood owned by a guild",
        "Previously closed with a door plug - maybe tomb or compound itself",
        "The plug is covered with what looks like surgeon tools",
        "a. Bench tombs;",
        "b. The plug stone with medical tools (collegia funeratica);",
        "c. Plug stone with libation hole (honey, milk and wine).",
        "Additional NotebookLM notes to add",
        "• Medieval Transformation: In the 13th century, an open space in the catacombs was recut to serve as a Christian shrine or rock-cut church.",
        "• Architectural Detail: The space includes Doric-style pillars and capitals joined by a frieze running around the chamber.",
        "• The Frescoes: The apse includes a 3rd-century fresco of a scallop shell painted in red, ochre and green, symbolising the “source of life”.",
        "• Christian Symbolism: The Chi-Rho monogram, made from the first two letters of Christ in Greek, appears with the Alpha and Omega, meaning Christ as the beginning and the end of life.",
        "Additional YouTube notes to add",
        "After the catacombs stopped being used mainly for burial, they were reused in several ways. Some reuse damaged the site, while other reuse created important later religious spaces.",
        "The end of the Byzantine period marked the end of the site’s use as a cemetery. There is little evidence for Muslim-period use. The next clear phase is late medieval, when parts of the catacombs became small churches or oratories during the re-Christianisation of Malta around the thirteenth century.",
        "Some tomb chambers were reused as churches and monastic spaces. Abbatija tad-Dejr, whose name means roughly 'the abbey', is one of the oldest underground church sites in Malta. Some areas of St Paul’s also served this kind of religious purpose.",
        "Christianity is visible through symbols such as the cross, palm branch, fish and anchor, and through later medieval reuse. However, the site was not exclusively Christian: pagans, Christians and Jews all used underground burial spaces in the wider cemetery.",
        "The popular idea that catacombs were secret hiding places for persecuted Christians is challenged by the transcript. The Romans knew where the catacombs were, and these were cemeteries, not practical refuges.",
        "The St Agatha hiding tradition belongs to this wider world of popular belief. Even if these stories are exaggerated or fictional, they shaped local memory and publications.",
        "Looters and treasure hunters damaged many catacombs. Looting was so widespread that some Grand Masters even issued licences to treasure hunters to search for gold on their behalf.",
        "The soft stone also made catacombs vulnerable to quarrying and reuse. Farmers converted some chambers into animal pens, modified tombs into feeding troughs and cut new features into the original architecture.",
        "During World War II, catacombs were used as air-raid shelters. In some clusters, such as St Augustine’s, wartime inscriptions survive. Artefacts from the Domus Romana were also moved into catacombs for protection.",
        "Today the catacombs are valued as archaeological sites, and visitor revenue helps support their preservation for future generations."
      ]
    },
    "9": {
      "title": "Jewish Hypogea",
      "paragraphs": [
        "Rituals, Conservation and architecture pavilions",
        "Western Sections",
        "selection of catacombs from across the road:",
        "a. Catacomb 6 with carvings of palm leaves and cross;",
        "b. Catacomb 8 with original skeletons in place, DNA from which has",
        "secured a date of 560 – 650 AD;",
        "c. Catacomb 10 with Jewish Menorah & original door (damaged by a bomb",
        "blast during World War II);",
        "d. Catacomb 12 with menorah & extensive use of window tomb.",
        "Next to the compound you can see which religion the compound belonged to.",
        "12 - 14 seems to be area of the Jewish Tombs - can see the cipher menorah (candlestick holder with 7 candles)",
        "Approximately 2000 year old symbol",
        "We do not know why it had 7 sticks: maybe 7 days of creation or the week, or 7 prophets? After explaining this, she suggested not discussing the symbolism of religion",
        "Judaism is the first monotheistic religion - big shift from pagan past",
        "Clustered in this area - shows community, also in same complex. Shows us no reel distinction between Jews or Christians as they had right to bury in same area together - they were equal.",
        "There are differences:",
        "Jews:",
        "total absence of agape table - therefore no feasting",
        "Relatively plain compared to Christian & pagan ones",
        "Less decorative features",
        "Burial rites much simpler than other rites",
        "No. 13 Compound",
        "She takes people here",
        "Easier to go round, rather easiest to see the menorah",
        "She said page 264 of bonanno book discusses it",
        "Look at the top of the entrance for the number of the compound",
        "Pavilions - most interesting one is the social one",
        "These inspired stories ex. Literature about underworld, Christian persecutors, martyrs etc.",
        "Story to be proud of: the Christopher Colombus of catacombs in Rome was Maltese (c. 1629) Antonio Bosio. Raised here in Malta then moved to rome to study. He was very interested in Catacombs and spent all his life studying them, making wonderful discoveries.",
        "He decided martyrs and persecuted Christians were buried in catacombs and so were holy. This started martydom mania - uncovering bones and selling them as pieces of saints. Church would instantly acquire statues if they had saint bones - people would go there to pray.",
        "Audio visual",
        "Onorato bres and cesare vassallo and achille ferris and antonio annetto caruana",
        "St payl church inwards, city of the living",
        "Outside, city od the dead",
        "Most christian feasts are rooted in pagan origins",
        "Additional NotebookLM notes to add",
        "• Community of Equal Status: The Jewish hypogea are located within the same general necropolis as Christian and pagan burials, showing communities living and dying in proximity and relative peace.",
        "• Identification: Hypogea 10, 12, 13 and 14 are marked by the menorah, the seven-branched candlestick, etched or painted at entrances.",
        "• Ritual Differences: Jewish hypogea contain no Agape tables, indicating that this community did not practise the refrigerium funerary meal.",
        "• Hypogeum 13: Contains an inscription for a gerousiarch, the head of a Council of Elders, and his wife Eulogia, who held the title presbytera, or elder.",
        "• Hypogeum 14: Contains an imposing baldacchino tomb decorated with a sailing vessel, possibly marking the grave of a wealthy merchant trading between Malta and Sicily.",
        "Additional YouTube notes to add",
        "Jewish burial in Rabat is mainly recognised through the menorah, the seven-branched candlestick. It is the key symbol indicating Jewish presence or ritual and appears in catacombs used by the Jewish community of Melite between the fourth and eighth centuries AD.",
        "Jewish funerary practice is harder to reconstruct than pagan Roman or Christian practice, but the catacombs show that Jewish communities did not assimilate Roman customs in the same way as Christians did.",
        "A major difference is the absence of triclinia in catacombs with Jewish symbols. This suggests that Roman-style funerary meals were not part of Jewish burial ritual.",
        "Cremation was not permitted. The body had to be buried in the ground as quickly as possible, unlike longer pagan displays of the body.",
        "Jewish funerals were generally simpler and more intimate. They may have included immediate relatives tearing garments to symbolise loss, psalms, a eulogy regardless of social status, a memorial prayer and a simple procession of pallbearers and mourners.",
        "The Jewish hypogea show the multicultural nature of the cemetery: pagans, Christians and Jews all buried their dead around Rabat, but ritual, architecture and symbols differed.",
        "The Conservation Pavilion can link to the fragility of evidence. Although many tombs were looted and accessible for centuries, modern excavation showed that useful in-situ remains survived. Conservation begins on site and continues in laboratories through cleaning, stabilisation and further controlled excavation when needed.",
        "The Architecture Pavilion can explain how architecture records community choices: absence or presence of triclinia, loculi, floor tombs, arcosolia, window tombs, baldacchino tombs, saddleback lids, cubicula with plug doors, locking systems, carved pillars, inscriptions, painted decoration and symbols. Together these reveal status, belief and ritual practice."
      ]
    }
  }
};
