window.domusFullNotes = {
  "tips": [
    "Tips:",
    "Good guiding practice – be sensitive to your group.",
    "Weather; example if it is raining, move the group inside but if it is cold you may place them in the sun. This location has narrow spaces so if you can stay outside for the introduction, it is better.",
    "Be careful not to block passages, at all times.",
    "It also depends on the number of people in the group.",
    "Use eye contact to figure if people are enjoying themselves and how to adapt.",
    "Check if they are engaged.",
    "Guiding requires a high element of entertainment.",
    "Move away from entrance and passage ways.",
    "If there is audio or guide with a mic, move away."
  ],
  "stops": [
    {
      "number": 1,
      "heading": "Entrance 1920s portico - Introduction to Roman Malta – urban life the Domus Romana",
      "paragraphs": [
        "Weather permitting, takes place outside to the side, not blocking the entrance.",
        "What is the meaning of domus?",
        "It is Latin for townhouse – therefore; Roman townhouse.",
        "Erroneously previously, and sometimes still, referred to as Roman villa. In Malta, customs and saying take long to die out.",
        "Located in the heart of the city of Melite, it is found on a hill, 187m above sea levels. Romans built town with a wall in ancient Melite.",
        "Documents are fragmentary, revealing very little about the composition etc of the town. Again, despite being in history, what we have is very little. Therefore understanding of how this town is problematic. Very little remains.",
        "A.A. Caruana: discovered place in 1881-1882",
        "He is the same person who cleared the catacombs.",
        "He built what is the first known structure to protect and conserve – a site with a kind of museum. It is not the one we see at the entrance but rather the one with blue walls around the mosaic area.",
        "In 1925 the portion at the back was built up, and the one at the front came even later. It was built up in different stages. It is where Roman artefacts were first placed. Not all items were found in this specific site, the coins however were found here.",
        "This makes the site unique, as it houses the only tangible remains of the town of Melite.",
        "The modern museum has not only Roman but also a cemetery with remains from the Islamic period in Malta. This period was 870-1091 CE, officially, but tomb and practices existed well into the 12th century. The cemetery dates to the 11th Century CE, possible before the Normal conquest.",
        "Fatimide vs aglebide",
        "Timeline:",
        "218- 500CE – Roman (arrived after the 2nd Punic War)",
        "500-870CE - Byzantine",
        "870-1091 CE – Arab",
        "There are very little physical remains of the Roman era. There is even less of the Byzantine. Sometimes referred to as a “dark era” due to lack of information, and lasts well into the 9th and 10th Centuries.",
        "This means there are very few TVPs - not tangible.",
        "The domus was used from circa the 1st Century BCE – 2nd Century CE.",
        "In a rustic manner, probably till the 5th Century CE.",
        "1st section is the Islamic cemetery explanation, then Roman. In between we see the statue which provides a nice explanation on emerging culture, then coins, Roman culture, mosaic and Anetto’s Museum.",
        "Anetto made plans of what he saw, however, Sir Temi Zammit documented his excavations in greater detail. Therefore, we have an idea of the site plan because of Anetto but not much detail on the excavations.",
        "For introduction explain:",
        "Area",
        "Brief Roman history",
        "Tour route",
        "Inside",
        "Site Discovery",
        "Different scholars or dilettante (not all were archaeologists) – CHIARA CHECK photo of board",
        "Showcase contains a copy of Sir Temi Zammit’s notebook; distinguishable due to particular style of writings and picture drawings.",
        "Original housed in Heritage Malta archives"
      ]
    },
    {
      "number": 2,
      "heading": "Islamic Section",
      "paragraphs": [
        "The 1st two showcases contain Islamic remains found in Mdina in the 1990s.",
        "Very little remains of this period.",
        "Technically it is only a 200 year period but Islam traditions & customs persisted well into the 12th Century.",
        "From the year 500 onwards, there was the spread of Islam globally. It came from the East, moving towards the West; from areas like Syria and Egypt into the Maghreb region (Libya and Tunisia). (Maghreb means West). After the Maghreb, they went up to Spain, Sicily, then Malta. Malta was a late conquest.",
        "Did the Arabs conquer the East to West for Islamic zeal?",
        "No, it was to increase wealth, resources and military power. Islamic came to conquest.",
        "Conquest of the Maghreb was resisted as it was Barber land. Eventually, were merged into the Arabic empire and assimilated.",
        "Most importance influence form the Arabs on Malta:",
        "Language",
        "City names",
        "This came from the Sicilian channel, not the Maghreb one.",
        "Also, had a migratory group which took advantage of new lands.",
        "Showcases contain fragments of ceramic pot, loom weights, ring with Arabic script (this found in tomb here).",
        "Painting on Wall",
        "Colour coded part shows where Melite used to span to: blue wall is the street in front of the church of St Paul.",
        "Melite was reduced to Mdina; moving from red to yellow area of the map.",
        "Traditionally, it is said that the Arabs reduced the size of the old Roman city. This is not known for certain, as it may very well have been a Byzantine change. Byzantine history shows that they reduced town sizes wherever they went, making them easier to defend.",
        "Therefore, the 2 theories are it could have happened before or after the Arab invasion. It is not our job to decide.",
        "In Arabic:",
        "Mdina – walled city",
        "Rabat – Islamic base",
        "We know very little about the Byzantine era. Mostly from artefacts found at tas-Silg and San Pawl Milqi.",
        "It seems that there was resistance when the Arabs took over as the little remains indicate destruction.",
        "Malta was also described as an uninhabited ruin during this time (500-870 CE)",
        "It may also explain why the city could have been reduced.",
        "1990s excavations contest this description because of the three sites mentioned.",
        "She mentioned Abatija tad-dejr for Byzantine.",
        "Al himyari wrote much after the Arabic period; 1400s.",
        "He clearly replicated Al Bakri: could be that Al Bakri said a story to make Normans appear nicer and Al Himyari took it a step further.",
        "This is colourful history – the more colourful, the more is strays from the truth.",
        "Here 1 of the 2 most significant remains of the Arab period in Malta was found here:",
        "Cemetery",
        "Pot of Arabic coins in 1698 / end of 17th Century (not found here)",
        "Maymunah stone: she said we are not sure if this was made here or simply brought here. Therefore, the focus on the previous two items.",
        "Inner square – peristyle: can be seen through the window",
        "Tombs in garden: right side of archaeological site. Not all outside was a cemetery",
        "They face South/South East i.e. facing Mecca",
        "They had a simple burial:",
        "Body wrapped in a sheet / linen like shroud",
        "Placed in tomb without coffin",
        "Face always sidewards towards Mecca (like in photo on the wall & in reconstruction/tomb replica)",
        "We have 11 tomb stones, not all are on display. They contain Arabic or Islamic verses. Two types:",
        "Kufic type – comes from Kufa, Iraq",
        "Earliest script, examples of it are found in dome of Jerusalem",
        "Easily recognised – geometric, linear",
        "Like Maymunah stone",
        "Naskh (confirm name)",
        "Looser, more floral and free flowing writing",
        "This was used to transcribe the Quran",
        "In Malta both types were found."
      ]
    },
    {
      "number": 3,
      "heading": "Ashtart-Isis or Fortuna-Juno Statue and Coinage Section",
      "paragraphs": [
        "Article by prolific photographer Daniel Cilia discuses a statue in limesone of the Goddess Astarte. This once stood at the entrance of Mdina and it is said that children would spit at it during the Knights period to reject paganism. It had so much spit on it that it turned black and was called the dark one. It is said that it was moved to the Domus.",
        "https://timesofmalta.com/article/curious-features-of-mdina.703114",
        "This statue here is not the same one described: this one is made of marble.",
        "it was found between the domus and Melite.",
        "What does it represent?",
        "Dated to the Roman period. Some say it is Isis (Egyptian), others Astarte (Punic). We do not know, but both are goddesses of motherhood and fertility.",
        "Imp. Decoration",
        "Clearly shows Punic influences were transported to the Roman period",
        "The Romans were polytheistic: nearly all countries in they conquered in the Mediterranean were example Carthage.",
        "To make sure the gods were on their side for prosperity and conquest, when they would find more gods they would simply add them to their gods. This was to protect them from the situation where the god they eliminated turned out to be the true god.",
        "This tradition to embrace other gods in their culture or religion can be seen in this statue since the style is clearly not Roman.",
        "Window provides a sneak peek:",
        "note the level of Melite was much lower than what we have today.",
        "Therefore, Mdina is a city built on a previous city: multilayered",
        "Coins",
        "Found in the Domus",
        "Do not explain all the timeline – just wow factors",
        "Malta coinage has a history of circa 2,500 years.",
        "Oldest coin is from Carthaginian/Punic Period, with Anan written on it:",
        "Most interesting; Malta was a municipum but had the right in this period when the house was occupied to mint and have its own coins. This means there was enough trading & commerce going on here that called for a mint – Bronze coins. Significant trade on island.",
        "When this house was alive, after all coins found elsewhere (Chiara I’m not sure what you wrote here). Found evidence / symbols on coins that indicate Punic, Roman & Sicilian elements. Example a Punic symbol with the word Melite stamped on it.",
        "Eventually this was stopped.",
        "Why do we think Rome sort of gave municipiums coins then removed them?",
        "They were a form of social media or propaganda: emperor’s face placed on coins.",
        "He could promote himself to all areas of his empire; how else would they know about him?",
        "They would also contain monuments, emphasising the greatness of the empire.",
        "When the emperor changed, the coins would change and previous ones became illegal.",
        "One of the best archaeological sites are rubbish dumps"
      ]
    },
    {
      "number": 4,
      "heading": "Roman families and Roman life",
      "paragraphs": [
        "Poster tells us about family",
        "Elite families, not poor people, country people or slaves. The elite were governed by the father: pater familias.",
        "This led to the creation of the patriarchal society",
        "Even in religion, God is a man",
        "Man took care of business",
        "Woman also had a role: manage the servants, food, etc., basically administerial role in the house",
        "I said sort of like the HR of the family",
        "TVP: not hairpins but used to write: stylus",
        "They would write on a piece of stone, rub it off with sand paper and were then able to reuse it.",
        "Baby rattle: very cute as these are still in use today",
        "Mask: grotesque made of terracotta – theatrical performances",
        "some found in tombs; suggested to chase of evil spirits (Chiara see how we can compare to the Zebbug and Phoenician faces in Museum of Archaeology)",
        "Pots – perfume, oil and lotions for hair, body, face, basically everything.",
        "Buckles and bracelets; show they enjoyed beautifying their person",
        "This section can be compared to the beauty salon.",
        "Video of sweet lady",
        "Museum opened in 1882",
        "closed during WW2 – used as a laboratory and storage",
        "1945 reopened",
        "During the 1940s, the family of the curator were residents here: a little during the war and a little after it was reopened.",
        "The lady is the curator’s daughter, and she is describing living in this/her house.",
        "CHIARA CHECK look up video",
        "Different types of jars – also called unguentaria",
        "Contained lotions, creams even embalming liquids.",
        "Smaller tear jars for mourners also found here.",
        "Shiny – not original coting; oxidation between the limestone and where they were buried.",
        "She can safely say that all crafts originated in Ancient Egypt example mosaic, glass blowing, pottery making (for decorative purposes not purely for use like in prehistory).",
        "Remember, these are copy cat cultures.",
        "Kitchen",
        "This was supervised by the lady of the house: had kitchen staff.",
        "Items in showcase include cauldrons and kitchen equipment.",
        "Some found here, others around area of Mdina and Rabat.",
        "Other showcase – dining room or table equipment",
        "Kitchen – ordinary items",
        "Dining – sophisticated; items self-explanatory",
        "Special / interesting item – glass flask",
        "Looks like snail shape",
        "drinking flask, may be passed on",
        "enabled drinker to drink laying down without spilling",
        "Classically trained poets and writers at the time would have been exposed to a few sources that painted ancient Romans as just the sort of people who would vomit just to eat more. One source was Seneca, the Stoic who lived from 4 B.C. to A.D. 65 and who gave the impression that Romans were an emetic bunch. In one passage, he wrote of slaves cleaning up the vomit of drunks at banquets, and in his Letter to Helvia, he summarized the vomitorium idea succinctly but metaphorically, referring to what he saw as the excesses of Rome: \"They vomit so they may eat, and eat so that they may vomit.\""
      ]
    },
    {
      "number": 5,
      "heading": "Emperor Claudius and his family Members",
      "paragraphs": [
        "Claudia Antonia CHIARA CONFIRM NAME",
        "Daughter of Emperor Claudius",
        "When speaking here, make sure to link this statue to the ones we are about to see below",
        "This statue was found alongside other family members of Claudius: who can be seen from the window",
        "The stairs lead to the house built in 1 Century BCE",
        "Used by aristocratic families till the 2nd Century CE.",
        "After it was used randomly by families not as elite or aristocratic etc.",
        "Blue walls are those built by Annetto",
        "Here we have a wonderful soap opera, not a TV one but a real one.",
        "It is based on Emperor Claudius and his family.",
        "He lived at the end of the 4th to the early 5th Century CE. He was not supposed to become emperor: he was disabled, had cerebral paulsy, walked with a limp, stammered and other things. He is the first emperor of Rome born outside of Italy: Lyon, France.",
        "He was hidden by his family because of his disabilities for all his childhood and early teens. This waws norm at the time.",
        "When the last healthy teen male of the family was assisinated, there was no one else and so he became emperor. Everyone thought he would be an unfit one, but he proved them wrong.",
        "Despite physical limitations, he was highly educated; spent his time hidden away studying and used that knowledge to restore empire which was facing great difficulties due to corruption and previous unfit rulers.",
        "He did many things, such as started the conquest of Brittain (in fact one of his children was named Brittanicus).",
        "He was instrumental in the building of aqueducts and canals. He did well.",
        "He was married 4 times and had 4 children from his first 3 wives.",
        "Boy, girl, girl, boy – CHIARA CHECK NAMES",
        "3rd wife quite famous: Messalina",
        "Known for being promiscuous and pornographic person.",
        "She was executed.",
        "Agrippina 4th wife is seen here (the second statue on the left)",
        "She had a son Nero who she made sure Claudius adopted.",
        "She took matters into her own hands – intruded into Claudius’ domain",
        "It is traditionally believed that she got rid of him by poisoning him (CHIARA CHECK why you wrote 54)",
        "If she was crafting & cunning, Nero was the same plus more ambitious.",
        "He killed his mother to stop her from interfering, then became emperor in a blood paved manner.",
        "He was a bad emperor; cruel, violent, killed so many -making it a dark period in Roman history",
        "He was killed brutally by the senate (CHIARA CHECK THIS)",
        "A very happy ending",
        "A. Bonanno thinks that this house belonged to someone of political power since he had the statues of the governors in his house.",
        "Through these statues, some sort of dating could also be done.",
        "These were decorated in the peristyle or main part of the house."
      ]
    },
    {
      "number": 6,
      "heading": "House Plan The ‘domus’ talk about the floor plan- the courtyard and the mosaics",
      "paragraphs": [
        "This has puzzled classical historians for decades. With the exception to 2 rows of stone, no walls survive of the floor plan, only this.",
        "With no walls, we cannot understand how it was.",
        "Campaign region, pompei, Aquelano are the best example of what Roman houses may have looked like.",
        "Some things are repeated but there was not one set template. Therefore, figuring out how this worked was hard work requiring more study.",
        "Domus would have outer garden, with a kind of area with some building. May have been tavern, bakery or some business to maintain the house. Silos and atrium may be found too.",
        "Domus Romana is inward looking building, with private sections.",
        "Areas where pater familias did business, negotiations and met people – in the peristyle",
        "Atrium – was like a waiting room outside",
        "Peristyle – meeting room",
        "The house once was wonderfully decorated, murals niches with gods, coloured plasters, with marble statues. Imagine it richly decorated.",
        "Now it is just barebones.",
        "Where was the entrance?",
        "Recent studies suggest it is where you can see the arch.",
        "Mosaics are not the terracotta tiles that lay on top, but the geometric designs at the side. The terracotta were added later by lower class repurposing the space: multilayered.",
        "Oppus scotulatum – at the centre (losange shape)",
        "Entrance hall- where the terracotta",
        "Guest welcoming area: Near statues, held rooden couches where guests could be refreshed; be given wine and refreshments.",
        "Like the lobby",
        "We do not have an atrium here according to the last detailed studies. It would have been outside the arch but we have no remains of one.",
        "This was a living house, office and workplace.",
        "We are in the guest area, not the private quarters (il bicca hdej il lift)",
        "Mosaics",
        "Position your guests in front of the door to the viewing platform to be able to see clearly.",
        "Peristyle: heart of Roman building",
        "Surrounded by limestone columns, only bits survived. Doric style",
        "Most complete composition that we have; others are not so complete.",
        "They are amgonst the oldest and best preserved in Europe, alongside those found in places like Pompeii",
        "Mosai production – most common people think square shape:",
        "Opus tessalatum – tessale means squares in latin: seen at outer part or frame",
        "Roughly 1x1cm in size",
        "Opus vermiculatum – verme means worm: miniscule, very small used to compose emblematic picture in the middle",
        "On the side we can point out clear example of these.",
        "They were not made in Malta. There were 3 main tile making locations:",
        "Bergamum in Asia Minor, today’s Turkey",
        "Antioche, Syria",
        "Alexandria Egypt",
        "She wants us to know this",
        "Had teams of travelling salesmen with brochures or booklets of what they had to offer including prices. They would visit the pater familia, maybe in the peristyle. They would make the order, send the order with a messenger to the workshop, the tiles would be prepared and the order would be shipped to the house together with the tile layer workers.",
        "Emblemata takes form of golden bowl with 2 doves",
        "Similar to Pompeii",
        "Hadrian’s villa outside Rome also had doves",
        "CHIARA CHECK HOW MANY DOVES THEY HAD",
        "Drinking doves of Sosu – he invented the design/picture.",
        "He was a popular artist and it was a popular design – 4th Century BCE",
        "Roman artists loved it and kept using it.",
        "It was used in peristyles as part of water collection structure.",
        "Could have had partial coverage.",
        "Idea of water is a very common theme going down even to Arab culture – it was integral to them.",
        "Impluvium – ceiling somehow collected water then chanelled to some kind of bowl or basin where the doves are",
        "Many houses in Rome had cisterns but this did not. It is reinforced by the presence of big amphorae.",
        "Cavity near white board may have been used to store wheat or other products. It could be the other way round i.e. that was for water and the bowls were for wheat etc.",
        "Unstable information – too little found",
        "Around where mosaics examples would have been the private rooms",
        "Story of Satyr & the Maends",
        "May have inspired Samson & Delilah",
        "CHIARA CHECK",
        "Water channel – pipes & jugs",
        "Honey pot",
        "Longer necks – the liquid was more fluid, or thinner ex wine",
        "Shorter necks – thicker liquid like honey and oil",
        "Reason would have been how much room they needed for “splashing”"
      ]
    },
    {
      "number": 7,
      "heading": "Outdoor section – The Olive press– Remains of subordinate Houses",
      "paragraphs": [
        "Excavations have not ended; every summer excavations continue in the garden which provide new discoveries.",
        "On the left, other Roman houses – not aristocratic, lesser quality and maybe bakery or other business.",
        "Large space – think it could have been the atrium.",
        "Ashlar blocks – Roman masonry",
        "You can see Mtarfa across the road",
        "Believed to have the temple of Prosperina",
        "imp a lot of dismantling took place at Roman sites for the buildings in Valletta, Grand Master’s palace, St John’s etc. – repurposing",
        "Magna Curia Castellania",
        "What survived of Roman era is:",
        "Country life – ex ta Kaccatura, San Pawl Milqi",
        "Town life – domus romana",
        "After life – catacombs",
        "No religious or institution survived.",
        "We found olive presses"
      ]
    },
    {
      "number": 8,
      "heading": "Islamic Cemetery – Proceed indoors and talk about amphorae, the different types of columns and frieze decorations",
      "paragraphs": [
        "[In 1899, although investigations had shown the archaeological importance of this site, a road leading to the new railway station was constructed. The road cut through the left side of the Roman ruins, destroying a good portion of the Roman remains, presumably even Islamic burials.] Tombs on the right side",
        "Found / excavated when building road arriving at the bottom of the hill for the train station i.e. destroyed by them.",
        "Used amphorae no longer usable / broken, beneath floor for insulation; less damp and cold.",
        "Lanterns lit up the place",
        "Signs the house was a luxurious house (residence and workplace) belonging to a military or politically important person. This person probably would have been buried in a saddle back tomb.",
        "Richly decorated, capitals – reminents of the top parts of columns",
        "3 columns: doric, Corinthian and ionic.",
        "These can be mixed and have a specific name, commonly known as composite order",
        "Intricate decorations – frieze"
      ]
    }
  ]
};
